version: "3.8"
#==================================================
services:
  ssl-localhost-nginx:
    hostname: ssl.localhost
    image: nginx:1.21-alpine
    container_name: ssl-localhost-nginx
    ports:
      - 127.0.0.1:20443:443
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # environment:
